baseURL = "/"
languageCode = "en-us"
title = "Freedom Boats Mallorca - Puerto Portals"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id="G-6CR4NKB92Z"

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Freedom Boats Mallorca"

  [params.homepage_meta_tags]
    meta_description = "Freedom Boats, charter brand new 8m boats with 250HP outboard engine in Puerto Portals, Mallorca."
    meta_og_title = "Freedom Boats - Day Charter in Puerto Portals, Mallorca"
    meta_og_type = "website"
    meta_og_url = "https://www.f-boats.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Freedom Boats, charter brand new 8m boats with 250HP outboard engine in Puerto Portals, Mallorca."
    meta_twitter_card = "summary"
    meta_twitter_site = "@freedom-boats"
    meta_twitter_creator = "@freedom-boats"

[[menu.main]]
	name = "Our Boats"
	url = "/our-boats/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Book Now"
    url = "/book-now/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
